### ISSUE TITLE
App is Janky

### ISSUE THREAD

**Issue by amanv8060** [TallyAssist/BizAssit#14]
App is Janky , Email should be verified before giving acess to app . Onboarding Screen is not responsive .
 This is a great business Idea .  I know You Guys are Sufficient for this , but would still love to be a part of this .

PR Related to the issues mentioned above as soon as i understand how is flow actually flowing in these 60k lines of code

**Comment by analyticalmonk** [comment]
Hi @amanv8060, thanks for reporting the bugs. We're not actively maintaining this project so feel free to open issues for individual bugs and take them up.
If you need any help understanding the flow, please let me know.
