### ISSUE TITLE
Project cannot run show lots of errors

### ISSUE THREAD

**Issue by Prajwan** [TallyAssist/BizAssit#15]
![Capture](https://user-images.githubusercontent.com/40496423/135393163-eab06a84-857d-4690-bb0e-f5aa9809dcba.PNG)

**Comment by RichaVerma** [comment]
Hi @Prajwan - the project is quite old, so maybe the libraries have updated a bit from there. Looks like only one library "auth" is throwing errors. You might wanna change that.
